[settings]
	class = "Abi"
	# doc_group = "20-Routes"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "1040-containers"
	ui_route = "1040-abis"
	parent = "sharing"
	attributes = "wantsSearch|wantsEnter|wantsModify"
	sorts = "isEmpty+Asc,isKnown+Asc,address+Asc"
	cache_type = "cacheable"
	cache_by = "range"
