[settings]
	class = "Config"
	# doc_group = "02-Chain Data"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "200-containers"
	attributes = "itemType=configTypes.Config"
	# produced_by = "blocks"
	# contains = "transaction, withdrawal"
	cache_type = "cacheable"
	cache_by = "range"
