[settings]
    class = "Daemon"
    # doc_group = "20-Routes"
    # doc_descr = "block data as returned from the RPC (with slight enhancements)"
    doc_route = "1090-containers"
    ui_route = "1090-daemons-0"
    attributes = "embedType=daemons.Daemon|noChain|noSdk|noPaging"
    # produced_by = "blocks"
    # contains = "transaction, withdrawal"
    cache_type = "cacheable"
    cache_by = "range"
