[settings]
    class = "Daemon"
    doc_route = "1090-containers"
    ui_route = "1090-daemons-7"
    ui_icon = "Server"
    attributes = "wantsZero"
    cache_type = "cacheable"
    cache_by = "range"
