[settings]
	class = "History"
	doc_route = "1010-containers"
	ui_route = "1010-history-2"
	ui_icon = "History"
	attributes = "wantsSearch|wantsZero|wantsMulti"
	children = "balances,incoming,outgoing,internals,charts,logs,statements,neighbors,traces,receipts"
	cache_type = "cacheable"
	cache_by = "range"
