[settings]
	class = "History"
	# doc_group = "20-Routes"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "1010-containers"
	ui_route = "1010-history-2"
	attributes = "itemType=coreTypes.Transaction|noSdk"
	search = "true"
	# produced_by = "blocks"
	# contains = "transaction, withdrawal"
	cache_type = "cacheable"
	cache_by = "range"
