[settings]
	class = "History"
	# doc_group = "20-Routes"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "1010-containers"
	ui_route = "1010-history-2"
	ui_icon = "BuildingMonument"
	attributes = "wantsSearch|wantsZero|wantsMulti"
	cache_type = "cacheable"
	cache_by = "range"
