[settings]
    class = "Index"
    doc_route = "1051-containers"
    ui_route = "1051-indexes"
    attributes = ""
    parent = "unchained"
    sorts = "range+Dec"
    cache_type = "cacheable"
    cache_by = "range"
