[settings]
    class = "Manifest"
    # doc_group = "20-Routes"
    # doc_descr = "block data as returned from the RPC (with slight enhancements)"
    doc_route = "1060-containers"
    ui_route = "1060-manifests-7"
    attributes = "itemType=types.ChunkRecord"
    sorts = "range+Dec"
    # produced_by = "blocks"
    # contains = "transaction, withdrawal"
    cache_type = "cacheable"
    cache_by = "range"
