[settings]
    class = "Manifest"
    doc_route = "1052-containers"
    ui_route = "1052-manifests"
    attributes = ""
    parent = "unchained"
    sorts = "range+Dec"
    cache_type = "cacheable"
    cache_by = "range"
