[settings]
	class = "Monitor"
	doc_route = "1025-containers"
	ui_route = "1025-monitors-3"
	ui_icon = "DeviceDesktop"
	attributes = "wantsSearch|wantsEnter|wantsModify"
	sorts = "nRecords+Asc,address+Asc"
	cache_type = "cacheable"
	cache_by = "range"
