[settings]
	class = "Name"
	# doc_group = "20-Routes"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "1030-containers"
	ui_route = "1030-names-4"
	attributes = "wantsSearch|wantsEnter|wantsModify"
	cache_type = "cacheable"
	cache_by = "range"
