[settings]
	class = "Name"
	doc_route = "1030-containers"
	ui_route = "1030-names"
	attributes = "wantsSearch|wantsEnter|wantsModify"
	parent = "sharing"
	cache_type = "cacheable"
	cache_by = "range"
