[settings]
    class = "Pin"
    doc_route = "1053-containers"
    ui_route = "1053-pins"
    ui_icon = "Pin"
    attributes = ""
    parent = "unchained"
    cache_type = "cacheable"
    cache_by = "range"
