[settings]
	class = "Session"
	# doc_group = "20-Routes"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "1100-containers"
	ui_route = "1100-session-u"
	attributes = "embedType=coreTypes.Session|noChain|initChain|noPaging"
	# produced_by = "blocks"
	# contains = "transaction, withdrawal"
	cache_type = "cacheable"
	cache_by = "range"
