[settings]
	class = "Settings"
	# doc_group = "02-Chain Data"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "120-containers"
	attributes = "itemType="
	# produced_by = "blocks"
	# contains = "transaction, withdrawal"
	cache_type = "cacheable"
	cache_by = "range"
	disable_go = true
