[settings]
    class = "Sharing"
    doc_route = "1050-containers"
    ui_route = "1050-sharing-4"
    ui_icon = "Share"
    attributes = "wantsSearch"
    children = "names,abis,uploads"
    cache_type = "cacheable"
    cache_by = "range"
