[settings]
    class = "Sharing"
    # doc_group = "20-Routes"
    # doc_descr = "block data as returned from the RPC (with slight enhancements)"
    doc_route = "1045-containers"
    ui_route = "1045-sharing-4"
    ui_icon = "Tag"
    attributes = "wantsEnter|wantsSearch"
    children = "names,abis"
    cache_type = "cacheable"
    cache_by = "range"
