[settings]
	class = "Status"
	# doc_group = "02-Chain Data"
	# doc_descr = "block data as returned from the RPC (with slight enhancements)"
	doc_route = "110-containers"
	attributes = "embedType=coreTypes.Status|noChain"
	# produced_by = "blocks"
	# contains = "transaction, withdrawal"
	cache_type = "cacheable"
	cache_by = "range"
	disable_go = true
