[settings]
    class = "Unchained"
    doc_route = "1065-containers"
    ui_route = "1065-unchained-5"
    ui_icon = "LinkOff"
    attributes = ""
    children = "indexes,manifests,pins,uploads"
    cache_type = "cacheable"
    cache_by = "range"
