[settings]
    class = "Upload"
    doc_route = "1054-containers"
    ui_route = "1054-uploads"
    ui_icon = "Upload"
    attributes = ""
    parent = "unchained"
    cache_type = "cacheable"
    cache_by = "range"
