[settings]
    class = "Wizard"
    # doc_group = "20-Routes"
    # doc_descr = "block data as returned from the RPC (with slight enhancements)"
    doc_route = "1120-containers"
    ui_route = "1120-wizard-w"
    attributes = "noSdk"
    # produced_by = "blocks"
    # contains = "transaction, withdrawal"
    cache_type = "cacheable"
    cache_by = "range"
