// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['AbiContainer']['FinishUnmarshal']();
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['AbiContainer']['Model'](arg1, arg2, arg3, arg4);
}

export function NeedsUpdate(arg1) {
  return window['go']['types']['AbiContainer']['NeedsUpdate'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['AbiContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['AbiContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['AbiContainer']['Summarize']();
}
