// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['types']['Daemon']['GetState']();
}

export function Instance() {
  return window['go']['types']['Daemon']['Instance']();
}

export function IsRunning() {
  return window['go']['types']['Daemon']['IsRunning']();
}

export function Pause() {
  return window['go']['types']['Daemon']['Pause']();
}

export function Run() {
  return window['go']['types']['Daemon']['Run']();
}

export function ShallowCopy() {
  return window['go']['types']['Daemon']['ShallowCopy']();
}

export function Stop() {
  return window['go']['types']['Daemon']['Stop']();
}

export function String() {
  return window['go']['types']['Daemon']['String']();
}

export function Tick(arg1) {
  return window['go']['types']['Daemon']['Tick'](arg1);
}

export function Toggle() {
  return window['go']['types']['Daemon']['Toggle']();
}
