// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForEveryProjectContainer(arg1, arg2) {
  return window['go']['types']['DashboardContainer']['ForEveryProjectContainer'](arg1, arg2);
}

export function NeedsUpdate(arg1) {
  return window['go']['types']['DashboardContainer']['NeedsUpdate'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['DashboardContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['DashboardContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['DashboardContainer']['Summarize']();
}
