// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['IndexSummary']['FinishUnmarshal']();
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['IndexSummary']['Model'](arg1, arg2, arg3, arg4);
}

export function String() {
  return window['go']['types']['IndexSummary']['String']();
}

export function Summarize() {
  return window['go']['types']['IndexSummary']['Summarize']();
}
