// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NeedsUpdate(arg1) {
  return window['go']['types']['ManifestContainer']['NeedsUpdate'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['ManifestContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['ManifestContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['ManifestContainer']['Summarize']();
}
