// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function ForEveryMonitor(arg1:types.EveryMonitorFn,arg2:any):Promise<boolean>;

export function NeedsUpdate(arg1:boolean):Promise<boolean>;

export function ShallowCopy():Promise<types.Containerer>;

export function String():Promise<string>;

export function Summarize():Promise<void>;
