// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForEveryMonitor(arg1, arg2) {
  return window['go']['types']['MonitorContainer']['ForEveryMonitor'](arg1, arg2);
}

export function NeedsUpdate(arg1) {
  return window['go']['types']['MonitorContainer']['NeedsUpdate'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['MonitorContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['MonitorContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['MonitorContainer']['Summarize']();
}
