// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['MonitorSummary']['FinishUnmarshal']();
}

export function MarshalCache(arg1) {
  return window['go']['types']['MonitorSummary']['MarshalCache'](arg1);
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['MonitorSummary']['Model'](arg1, arg2, arg3, arg4);
}

export function ShallowCopy() {
  return window['go']['types']['MonitorSummary']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['MonitorSummary']['String']();
}

export function Summarize() {
  return window['go']['types']['MonitorSummary']['Summarize']();
}

export function UnmarshalCache(arg1, arg2) {
  return window['go']['types']['MonitorSummary']['UnmarshalCache'](arg1, arg2);
}
