// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['MonitorContainer']['FinishUnmarshal']();
}

export function MarshalCache(arg1) {
  return window['go']['types']['MonitorContainer']['MarshalCache'](arg1);
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['MonitorContainer']['Model'](arg1, arg2, arg3, arg4);
}

export function NeedsUpdate() {
  return window['go']['types']['MonitorContainer']['NeedsUpdate']();
}

export function ShallowCopy() {
  return window['go']['types']['MonitorContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['MonitorContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['MonitorContainer']['Summarize']();
}

export function UnmarshalCache(arg1, arg2) {
  return window['go']['types']['MonitorContainer']['UnmarshalCache'](arg1, arg2);
}
