// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function NeedsUpdate():Promise<boolean>;

export function ShallowCopy():Promise<types.Containerer>;

export function String():Promise<string>;

export function Summarize():Promise<void>;
