// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ShallowCopy() {
  return window['go']['types']['NameSummary']['ShallowCopy']();
}

export function Summarize() {
  return window['go']['types']['NameSummary']['Summarize']();
}
