// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NeedsUpdate() {
  return window['go']['types']['NameContainer']['NeedsUpdate']();
}

export function ShallowCopy() {
  return window['go']['types']['NameContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['NameContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['NameContainer']['Summarize']();
}
