// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Load():Promise<void>;

export function Save():Promise<void>;

export function ShallowCopy():Promise<types.PortfolioContainer>;

export function String():Promise<string>;

export function Summarize():Promise<void>;
