// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['types']['PortfolioContainer']['Load']();
}

export function Save() {
  return window['go']['types']['PortfolioContainer']['Save']();
}

export function ShallowCopy() {
  return window['go']['types']['PortfolioContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['PortfolioContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['PortfolioContainer']['Summarize']();
}
