// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForEveryAddress(arg1, arg2) {
  return window['go']['types']['ProjectContainer']['ForEveryAddress'](arg1, arg2);
}

export function Load(arg1) {
  return window['go']['types']['ProjectContainer']['Load'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['types']['ProjectContainer']['NeedsUpdate'](arg1);
}

export function Save(arg1) {
  return window['go']['types']['ProjectContainer']['Save'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['ProjectContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['ProjectContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['ProjectContainer']['Summarize']();
}
