// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['types']['ProjectContainer']['Load']();
}

export function NeedsUpdate(arg1) {
  return window['go']['types']['ProjectContainer']['NeedsUpdate'](arg1);
}

export function Save() {
  return window['go']['types']['ProjectContainer']['Save']();
}

export function ShallowCopy() {
  return window['go']['types']['ProjectContainer']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['ProjectContainer']['String']();
}

export function Summarize() {
  return window['go']['types']['ProjectContainer']['Summarize']();
}
