// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accumulate(arg1) {
  return window['go']['types']['SessionContainer']['Accumulate'](arg1);
}

export function CleanWindowSize(arg1) {
  return window['go']['types']['SessionContainer']['CleanWindowSize'](arg1);
}

export function Clear() {
  return window['go']['types']['SessionContainer']['Clear']();
}

export function CollateAndFilter(arg1) {
  return window['go']['types']['SessionContainer']['CollateAndFilter'](arg1);
}

export function Finalize() {
  return window['go']['types']['SessionContainer']['Finalize']();
}

export function ForEveryItem(arg1, arg2) {
  return window['go']['types']['SessionContainer']['ForEveryItem'](arg1, arg2);
}

export function GetAddress() {
  return window['go']['types']['SessionContainer']['GetAddress']();
}

export function GetChain() {
  return window['go']['types']['SessionContainer']['GetChain']();
}

export function GetFile() {
  return window['go']['types']['SessionContainer']['GetFile']();
}

export function GetFolder() {
  return window['go']['types']['SessionContainer']['GetFolder']();
}

export function GetItems() {
  return window['go']['types']['SessionContainer']['GetItems']();
}

export function GetRoute() {
  return window['go']['types']['SessionContainer']['GetRoute']();
}

export function GetTab(arg1) {
  return window['go']['types']['SessionContainer']['GetTab'](arg1);
}

export function GetWindow() {
  return window['go']['types']['SessionContainer']['GetWindow']();
}

export function GetWizardStr() {
  return window['go']['types']['SessionContainer']['GetWizardStr']();
}

export function IsFlagOn(arg1) {
  return window['go']['types']['SessionContainer']['IsFlagOn'](arg1);
}

export function Load() {
  return window['go']['types']['SessionContainer']['Load']();
}

export function MarshalJSON() {
  return window['go']['types']['SessionContainer']['MarshalJSON']();
}

export function NeedsUpdate() {
  return window['go']['types']['SessionContainer']['NeedsUpdate']();
}

export function Save() {
  return window['go']['types']['SessionContainer']['Save']();
}

export function SetAddress(arg1) {
  return window['go']['types']['SessionContainer']['SetAddress'](arg1);
}

export function SetChain(arg1) {
  return window['go']['types']['SessionContainer']['SetChain'](arg1);
}

export function SetFile(arg1) {
  return window['go']['types']['SessionContainer']['SetFile'](arg1);
}

export function SetFlagOn(arg1, arg2) {
  return window['go']['types']['SessionContainer']['SetFlagOn'](arg1, arg2);
}

export function SetFolder(arg1) {
  return window['go']['types']['SessionContainer']['SetFolder'](arg1);
}

export function SetItems(arg1) {
  return window['go']['types']['SessionContainer']['SetItems'](arg1);
}

export function SetRoute(arg1) {
  return window['go']['types']['SessionContainer']['SetRoute'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['types']['SessionContainer']['SetTab'](arg1, arg2);
}

export function SetWindow(arg1) {
  return window['go']['types']['SessionContainer']['SetWindow'](arg1);
}

export function SetWizardStr(arg1) {
  return window['go']['types']['SessionContainer']['SetWizardStr'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['SessionContainer']['ShallowCopy']();
}

export function Sort() {
  return window['go']['types']['SessionContainer']['Sort']();
}

export function String() {
  return window['go']['types']['SessionContainer']['String']();
}

export function UnmarshalJSON(arg1) {
  return window['go']['types']['SessionContainer']['UnmarshalJSON'](arg1);
}
