// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NeedsUpdate(arg1) {
  return window['go']['types']['SettingsGroup']['NeedsUpdate'](arg1);
}

export function ShallowCopy() {
  return window['go']['types']['SettingsGroup']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['SettingsGroup']['String']();
}

export function Summarize() {
  return window['go']['types']['SettingsGroup']['Summarize']();
}
