// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Step(arg1) {
  return window['go']['types']['Wizard']['Step'](arg1);
}
