// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wizard} from '../models';

export function Step(arg1:wizard.Step):Promise<void>;
