// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function GetBlock(arg1:number):Promise<app.Block>;

export function GetNames(arg1:number):Promise<Array<string>>;

export function GetSession():Promise<config.Session>;
