// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbiPage(arg1, arg2) {
  return window['go']['app']['App']['AbiPage'](arg1, arg2);
}

export function AccordionToggle(arg1) {
  return window['go']['app']['App']['AccordionToggle'](arg1);
}

export function AddrToName(arg1) {
  return window['go']['app']['App']['AddrToName'](arg1);
}

export function CancelAllContexts() {
  return window['go']['app']['App']['CancelAllContexts']();
}

export function CancelContext(arg1) {
  return window['go']['app']['App']['CancelContext'](arg1);
}

export function ConvertToAddress(arg1) {
  return window['go']['app']['App']['ConvertToAddress'](arg1);
}

export function ExportAddress(arg1) {
  return window['go']['app']['App']['ExportAddress'](arg1);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function FooterToggle(arg1) {
  return window['go']['app']['App']['FooterToggle'](arg1);
}

export function GetAddress() {
  return window['go']['app']['App']['GetAddress']();
}

export function GetAppTitle() {
  return window['go']['app']['App']['GetAppTitle']();
}

export function GetChain() {
  return window['go']['app']['App']['GetChain']();
}

export function GetChainInfo(arg1) {
  return window['go']['app']['App']['GetChainInfo'](arg1);
}

export function GetChains() {
  return window['go']['app']['App']['GetChains']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetDaemonJson(arg1) {
  return window['go']['app']['App']['GetDaemonJson'](arg1);
}

export function GetEnv(arg1) {
  return window['go']['app']['App']['GetEnv'](arg1);
}

export function GetExploreUrl(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetExploreUrl'](arg1, arg2, arg3);
}

export function GetMenus() {
  return window['go']['app']['App']['GetMenus']();
}

export function GetMeta() {
  return window['go']['app']['App']['GetMeta']();
}

export function GetRoute() {
  return window['go']['app']['App']['GetRoute']();
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function GetSessionDeamon(arg1) {
  return window['go']['app']['App']['GetSessionDeamon'](arg1);
}

export function GetWindow() {
  return window['go']['app']['App']['GetWindow']();
}

export function GetWizardState() {
  return window['go']['app']['App']['GetWizardState']();
}

export function GoToHistory(arg1) {
  return window['go']['app']['App']['GoToHistory'](arg1);
}

export function HeaderToggle(arg1) {
  return window['go']['app']['App']['HeaderToggle'](arg1);
}

export function HelpToggle(arg1) {
  return window['go']['app']['App']['HelpToggle'](arg1);
}

export function HistoryPage(arg1, arg2, arg3) {
  return window['go']['app']['App']['HistoryPage'](arg1, arg2, arg3);
}

export function IndexPage(arg1, arg2) {
  return window['go']['app']['App']['IndexPage'](arg1, arg2);
}

export function IsConfigured() {
  return window['go']['app']['App']['IsConfigured']();
}

export function IsShowing(arg1) {
  return window['go']['app']['App']['IsShowing'](arg1);
}

export function LoadName(arg1) {
  return window['go']['app']['App']['LoadName'](arg1);
}

export function ManifestPage(arg1, arg2) {
  return window['go']['app']['App']['ManifestPage'](arg1, arg2);
}

export function MenuToggle(arg1) {
  return window['go']['app']['App']['MenuToggle'](arg1);
}

export function ModifyAbi(arg1) {
  return window['go']['app']['App']['ModifyAbi'](arg1);
}

export function ModifyMonitors(arg1) {
  return window['go']['app']['App']['ModifyMonitors'](arg1);
}

export function ModifyName(arg1) {
  return window['go']['app']['App']['ModifyName'](arg1);
}

export function ModifyNoop(arg1) {
  return window['go']['app']['App']['ModifyNoop'](arg1);
}

export function ModifyProject(arg1) {
  return window['go']['app']['App']['ModifyProject'](arg1);
}

export function MonitorPage(arg1, arg2) {
  return window['go']['app']['App']['MonitorPage'](arg1, arg2);
}

export function NamePage(arg1, arg2) {
  return window['go']['app']['App']['NamePage'](arg1, arg2);
}

export function Navigate(arg1, arg2) {
  return window['go']['app']['App']['Navigate'](arg1, arg2);
}

export function ProjectPage(arg1, arg2) {
  return window['go']['app']['App']['ProjectPage'](arg1, arg2);
}

export function Refresh(arg1) {
  return window['go']['app']['App']['Refresh'](arg1);
}

export function RegisterCtx(arg1) {
  return window['go']['app']['App']['RegisterCtx'](arg1);
}

export function Reload(arg1) {
  return window['go']['app']['App']['Reload'](arg1);
}

export function SaveName(arg1) {
  return window['go']['app']['App']['SaveName'](arg1);
}

export function SetChain(arg1, arg2) {
  return window['go']['app']['App']['SetChain'](arg1, arg2);
}

export function SetEnv(arg1, arg2) {
  return window['go']['app']['App']['SetEnv'](arg1, arg2);
}

export function SetRoute(arg1, arg2) {
  return window['go']['app']['App']['SetRoute'](arg1, arg2);
}

export function SetSessionDaemon(arg1, arg2) {
  return window['go']['app']['App']['SetSessionDaemon'](arg1, arg2);
}

export function SetShowing(arg1, arg2) {
  return window['go']['app']['App']['SetShowing'](arg1, arg2);
}

export function StateToString(arg1) {
  return window['go']['app']['App']['StateToString'](arg1);
}

export function StatusPage(arg1, arg2) {
  return window['go']['app']['App']['StatusPage'](arg1, arg2);
}

export function StepWizard(arg1) {
  return window['go']['app']['App']['StepWizard'](arg1);
}

export function String() {
  return window['go']['app']['App']['String']();
}

export function SystemAbout(arg1) {
  return window['go']['app']['App']['SystemAbout'](arg1);
}

export function SystemQuit(arg1) {
  return window['go']['app']['App']['SystemQuit'](arg1);
}

export function ToggleDaemon(arg1) {
  return window['go']['app']['App']['ToggleDaemon'](arg1);
}

export function ViewAbis(arg1) {
  return window['go']['app']['App']['ViewAbis'](arg1);
}

export function ViewDaemons(arg1) {
  return window['go']['app']['App']['ViewDaemons'](arg1);
}

export function ViewHistory(arg1) {
  return window['go']['app']['App']['ViewHistory'](arg1);
}

export function ViewIndexes(arg1) {
  return window['go']['app']['App']['ViewIndexes'](arg1);
}

export function ViewManifest(arg1) {
  return window['go']['app']['App']['ViewManifest'](arg1);
}

export function ViewMonitors(arg1) {
  return window['go']['app']['App']['ViewMonitors'](arg1);
}

export function ViewNames(arg1) {
  return window['go']['app']['App']['ViewNames'](arg1);
}

export function ViewProject(arg1) {
  return window['go']['app']['App']['ViewProject'](arg1);
}

export function ViewSettings(arg1) {
  return window['go']['app']['App']['ViewSettings'](arg1);
}

export function ViewStatus(arg1) {
  return window['go']['app']['App']['ViewStatus'](arg1);
}

export function ViewWizard(arg1) {
  return window['go']['app']['App']['ViewWizard'](arg1);
}
