// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAllContexts() {
  return window['go']['app']['App']['CancelAllContexts']();
}

export function DaemonsView(arg1) {
  return window['go']['app']['App']['DaemonsView'](arg1);
}

export function ExportAddress(arg1) {
  return window['go']['app']['App']['ExportAddress'](arg1);
}

export function FetchAbi(arg1, arg2) {
  return window['go']['app']['App']['FetchAbi'](arg1, arg2);
}

export function FetchAppInfo() {
  return window['go']['app']['App']['FetchAppInfo']();
}

export function FetchBalance(arg1, arg2) {
  return window['go']['app']['App']['FetchBalance'](arg1, arg2);
}

export function FetchChart(arg1, arg2) {
  return window['go']['app']['App']['FetchChart'](arg1, arg2);
}

export function FetchConfig(arg1, arg2) {
  return window['go']['app']['App']['FetchConfig'](arg1, arg2);
}

export function FetchDaemon(arg1, arg2) {
  return window['go']['app']['App']['FetchDaemon'](arg1, arg2);
}

export function FetchIncoming(arg1, arg2) {
  return window['go']['app']['App']['FetchIncoming'](arg1, arg2);
}

export function FetchIndex(arg1, arg2) {
  return window['go']['app']['App']['FetchIndex'](arg1, arg2);
}

export function FetchInternal(arg1, arg2) {
  return window['go']['app']['App']['FetchInternal'](arg1, arg2);
}

export function FetchLog(arg1, arg2) {
  return window['go']['app']['App']['FetchLog'](arg1, arg2);
}

export function FetchManifest(arg1, arg2) {
  return window['go']['app']['App']['FetchManifest'](arg1, arg2);
}

export function FetchMonitor(arg1, arg2) {
  return window['go']['app']['App']['FetchMonitor'](arg1, arg2);
}

export function FetchName(arg1, arg2) {
  return window['go']['app']['App']['FetchName'](arg1, arg2);
}

export function FetchNeighbor(arg1, arg2) {
  return window['go']['app']['App']['FetchNeighbor'](arg1, arg2);
}

export function FetchOutgoing(arg1, arg2) {
  return window['go']['app']['App']['FetchOutgoing'](arg1, arg2);
}

export function FetchPin(arg1, arg2) {
  return window['go']['app']['App']['FetchPin'](arg1, arg2);
}

export function FetchProject(arg1, arg2) {
  return window['go']['app']['App']['FetchProject'](arg1, arg2);
}

export function FetchReceipt(arg1, arg2) {
  return window['go']['app']['App']['FetchReceipt'](arg1, arg2);
}

export function FetchSession(arg1, arg2) {
  return window['go']['app']['App']['FetchSession'](arg1, arg2);
}

export function FetchStatement(arg1, arg2) {
  return window['go']['app']['App']['FetchStatement'](arg1, arg2);
}

export function FetchStatus(arg1, arg2) {
  return window['go']['app']['App']['FetchStatus'](arg1, arg2);
}

export function FetchTrace(arg1, arg2) {
  return window['go']['app']['App']['FetchTrace'](arg1, arg2);
}

export function FetchUpload(arg1, arg2) {
  return window['go']['app']['App']['FetchUpload'](arg1, arg2);
}

export function FetchWizard(arg1, arg2) {
  return window['go']['app']['App']['FetchWizard'](arg1, arg2);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function Freshen() {
  return window['go']['app']['App']['Freshen']();
}

export function GetChainInfo(arg1) {
  return window['go']['app']['App']['GetChainInfo'](arg1);
}

export function GetChains() {
  return window['go']['app']['App']['GetChains']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function GetDaemon(arg1) {
  return window['go']['app']['App']['GetDaemon'](arg1);
}

export function GetEnv(arg1) {
  return window['go']['app']['App']['GetEnv'](arg1);
}

export function GetExploreUrl(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetExploreUrl'](arg1, arg2, arg3);
}

export function GetFilter() {
  return window['go']['app']['App']['GetFilter']();
}

export function GetHeaderOn(arg1, arg2) {
  return window['go']['app']['App']['GetHeaderOn'](arg1, arg2);
}

export function GetHistoryContainer() {
  return window['go']['app']['App']['GetHistoryContainer']();
}

export function GetLastAddress() {
  return window['go']['app']['App']['GetLastAddress']();
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetLastTab(arg1) {
  return window['go']['app']['App']['GetLastTab'](arg1);
}

export function GetMenus() {
  return window['go']['app']['App']['GetMenus']();
}

export function GetName(arg1) {
  return window['go']['app']['App']['GetName'](arg1);
}

export function GetState(arg1) {
  return window['go']['app']['App']['GetState'](arg1);
}

export function GetTabs() {
  return window['go']['app']['App']['GetTabs']();
}

export function HistoryView(arg1) {
  return window['go']['app']['App']['HistoryView'](arg1);
}

export function GetDaemonOn(arg1) {
  return window['go']['app']['App']['GetDaemonOn'](arg1);
}

export function GetLayoutOn(arg1) {
  return window['go']['app']['App']['GetLayoutOn'](arg1);
}

export function LoadAddress(arg1) {
  return window['go']['app']['App']['LoadAddress'](arg1);
}

export function LoadDalleImage(arg1) {
  return window['go']['app']['App']['LoadDalleImage'](arg1);
}

export function LoadName(arg1) {
  return window['go']['app']['App']['LoadName'](arg1);
}

export function Logger(arg1) {
  return window['go']['app']['App']['Logger'](arg1);
}

export function ModifyAbi(arg1) {
  return window['go']['app']['App']['ModifyAbi'](arg1);
}

export function ModifyMonitor(arg1) {
  return window['go']['app']['App']['ModifyMonitor'](arg1);
}

export function ModifyName(arg1) {
  return window['go']['app']['App']['ModifyName'](arg1);
}

export function ModifyProject(arg1) {
  return window['go']['app']['App']['ModifyProject'](arg1);
}

export function MonitorsView(arg1) {
  return window['go']['app']['App']['MonitorsView'](arg1);
}

export function Navigate(arg1) {
  return window['go']['app']['App']['Navigate'](arg1);
}

export function ProjectView(arg1) {
  return window['go']['app']['App']['ProjectView'](arg1);
}

export function Reload() {
  return window['go']['app']['App']['Reload']();
}

export function SetChain(arg1) {
  return window['go']['app']['App']['SetChain'](arg1);
}

export function SetDaemonOn(arg1, arg2) {
  return window['go']['app']['App']['SetDaemonOn'](arg1, arg2);
}

export function SetEnv(arg1, arg2) {
  return window['go']['app']['App']['SetEnv'](arg1, arg2);
}

export function SetFilter(arg1) {
  return window['go']['app']['App']['SetFilter'](arg1);
}

export function SetHeaderOn(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetHeaderOn'](arg1, arg2, arg3);
}

export function SetLastAddress(arg1) {
  return window['go']['app']['App']['SetLastAddress'](arg1);
}

export function SetLastRoute(arg1) {
  return window['go']['app']['App']['SetLastRoute'](arg1);
}

export function SetLastTab(arg1, arg2) {
  return window['go']['app']['App']['SetLastTab'](arg1, arg2);
}

export function SetLayoutOn(arg1, arg2) {
  return window['go']['app']['App']['SetLayoutOn'](arg1, arg2);
}

export function SettingsView(arg1) {
  return window['go']['app']['App']['SettingsView'](arg1);
}

export function SharingView(arg1) {
  return window['go']['app']['App']['SharingView'](arg1);
}

export function StepWizard(arg1) {
  return window['go']['app']['App']['StepWizard'](arg1);
}

export function SystemAbout(arg1) {
  return window['go']['app']['App']['SystemAbout'](arg1);
}

export function SystemQuit(arg1) {
  return window['go']['app']['App']['SystemQuit'](arg1);
}

export function ToggleAppFooter(arg1) {
  return window['go']['app']['App']['ToggleAppFooter'](arg1);
}

export function ToggleAppHeader(arg1) {
  return window['go']['app']['App']['ToggleAppHeader'](arg1);
}

export function ToggleAppHelp(arg1) {
  return window['go']['app']['App']['ToggleAppHelp'](arg1);
}

export function ToggleAppMenu(arg1) {
  return window['go']['app']['App']['ToggleAppMenu'](arg1);
}

export function ToggleDaemon(arg1) {
  return window['go']['app']['App']['ToggleDaemon'](arg1);
}

export function ToggleNextTab(arg1) {
  return window['go']['app']['App']['ToggleNextTab'](arg1);
}

export function TogglePrevTab(arg1) {
  return window['go']['app']['App']['TogglePrevTab'](arg1);
}

export function ToggleViewHeader(arg1) {
  return window['go']['app']['App']['ToggleViewHeader'](arg1);
}

export function UnchainedView(arg1) {
  return window['go']['app']['App']['UnchainedView'](arg1);
}

export function WizardView(arg1) {
  return window['go']['app']['App']['WizardView'](arg1);
}
