// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['App']['Cancel'](arg1);
}

export function ConvertToAddress(arg1) {
  return window['go']['app']['App']['ConvertToAddress'](arg1);
}

export function Fatal(arg1) {
  return window['go']['app']['App']['Fatal'](arg1);
}

export function FileNew(arg1) {
  return window['go']['app']['App']['FileNew'](arg1);
}

export function FileOpen(arg1) {
  return window['go']['app']['App']['FileOpen'](arg1);
}

export function FileSave(arg1) {
  return window['go']['app']['App']['FileSave'](arg1);
}

export function FileSaveAs(arg1) {
  return window['go']['app']['App']['FileSaveAs'](arg1);
}

export function GetAbisCnt() {
  return window['go']['app']['App']['GetAbisCnt']();
}

export function GetAbis(arg1, arg2) {
  return window['go']['app']['App']['GetAbis'](arg1, arg2);
}

export function GetExistingAddrs() {
  return window['go']['app']['App']['GetExistingAddrs']();
}

export function GetHistoryCnt(arg1) {
  return window['go']['app']['App']['GetHistoryCnt'](arg1);
}

export function GetHistory(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHistory'](arg1, arg2, arg3);
}

export function GetIndex(arg1, arg2) {
  return window['go']['app']['App']['GetIndex'](arg1, arg2);
}

export function GetIndexCnt() {
  return window['go']['app']['App']['GetIndexCnt']();
}

export function GetLast(arg1) {
  return window['go']['app']['App']['GetLast'](arg1);
}

export function GetManifest(arg1, arg2) {
  return window['go']['app']['App']['GetManifest'](arg1, arg2);
}

export function GetManifestCnt() {
  return window['go']['app']['App']['GetManifestCnt']();
}

export function GetMenus() {
  return window['go']['app']['App']['GetMenus']();
}

export function GetMonitorsCnt() {
  return window['go']['app']['App']['GetMonitorsCnt']();
}

export function GetMonitors(arg1, arg2) {
  return window['go']['app']['App']['GetMonitors'](arg1, arg2);
}

export function GetNamesCnt() {
  return window['go']['app']['App']['GetNamesCnt']();
}

export function GetNames(arg1, arg2) {
  return window['go']['app']['App']['GetNames'](arg1, arg2);
}

export function GetServer(arg1) {
  return window['go']['app']['App']['GetServer'](arg1);
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function GetStatus(arg1, arg2) {
  return window['go']['app']['App']['GetStatus'](arg1, arg2);
}

export function GetStatusCnt() {
  return window['go']['app']['App']['GetStatusCnt']();
}

export function HelpToggle(arg1) {
  return window['go']['app']['App']['HelpToggle'](arg1);
}

export function RegisterCtx(arg1) {
  return window['go']['app']['App']['RegisterCtx'](arg1);
}

export function SetLast(arg1, arg2) {
  return window['go']['app']['App']['SetLast'](arg1, arg2);
}

export function StartServers() {
  return window['go']['app']['App']['StartServers']();
}

export function StateToString(arg1) {
  return window['go']['app']['App']['StateToString'](arg1);
}

export function String() {
  return window['go']['app']['App']['String']();
}

export function SystemAbout(arg1) {
  return window['go']['app']['App']['SystemAbout'](arg1);
}

export function SystemQuit(arg1) {
  return window['go']['app']['App']['SystemQuit'](arg1);
}

export function ToggleServer(arg1) {
  return window['go']['app']['App']['ToggleServer'](arg1);
}

export function ViewAbis(arg1) {
  return window['go']['app']['App']['ViewAbis'](arg1);
}

export function ViewHistory(arg1) {
  return window['go']['app']['App']['ViewHistory'](arg1);
}

export function ViewHome(arg1) {
  return window['go']['app']['App']['ViewHome'](arg1);
}

export function ViewIndexes(arg1) {
  return window['go']['app']['App']['ViewIndexes'](arg1);
}

export function ViewManifest(arg1) {
  return window['go']['app']['App']['ViewManifest'](arg1);
}

export function ViewMonitors(arg1) {
  return window['go']['app']['App']['ViewMonitors'](arg1);
}

export function ViewNames(arg1) {
  return window['go']['app']['App']['ViewNames'](arg1);
}

export function ViewServers(arg1) {
  return window['go']['app']['App']['ViewServers'](arg1);
}

export function ViewSettings(arg1) {
  return window['go']['app']['App']['ViewSettings'](arg1);
}

export function ViewStatus(arg1) {
  return window['go']['app']['App']['ViewStatus'](arg1);
}
