// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';

export function String():Promise<string>;

export function WriteFile(arg1:string,arg2:version.Version):Promise<void>;
