// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WriteFile(arg1, arg2) {
  return window['go']['configtypes']['Config']['WriteFile'](arg1, arg2);
}
